// <auto-generated />
using System;
using Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615131205_AddClientes")]
    partial class AddClientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Modules.Bookings.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingStatusAccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeedbackAccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FeedbackSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalChargedPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("NoShowAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoShowReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OwnerContact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PetSpecies")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SlotEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SlotStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("EmpresaId", "ServiceId", "SlotStart");

                    b.HasIndex("EmpresaId", "ProfessionalId", "SlotStart", "State");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Bookings.Domain.BookingFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<int>("PetshopRating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProfessionalRating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("booking_feedbacks", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Bookings.Infrastructure.InboxEntry", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.ToTable("inbox_entries", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Clients.Domain.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Disponibilidade.Domain.DisponibilidadeProfissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ProfissionalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionalId");

                    b.ToTable("disponibilidades_profissionais", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Empresas.Domain.DomainNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Outcome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("outcome");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_domain_notifications_created_at");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_domain_notifications_empresa_id");

                    b.ToTable("domain_notifications", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Empresas.Domain.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bairro")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cidade")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("DominioPersonalizadoAtivadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_ativado_em");

                    b.Property<string>("DominioPersonalizadoAtivo")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("dominio_personalizado_ativo");

                    b.Property<bool>("DominioPersonalizadoCanonicoRevertidoParaFallback")
                        .HasColumnType("boolean")
                        .HasColumnName("dominio_personalizado_canonico_revertido_para_fallback");

                    b.Property<string>("DominioPersonalizadoDesejado")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("dominio_personalizado_desejado");

                    b.Property<string>("DominioPersonalizadoDnsStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dominio_personalizado_dns_status");

                    b.Property<DateTime?>("DominioPersonalizadoHttpsProntoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_https_pronto_em");

                    b.Property<DateTime?>("DominioPersonalizadoProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_proxima_tentativa_em");

                    b.Property<DateTime?>("DominioPersonalizadoProximoMonitoramentoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_proximo_monitoramento_em");

                    b.Property<string>("DominioPersonalizadoStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dominio_personalizado_status");

                    b.Property<DateTime?>("DominioPersonalizadoTlsProvisionamentoIniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_tls_provisionamento_iniciado_em");

                    b.Property<DateTime?>("DominioPersonalizadoTlsProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_tls_proxima_tentativa_em");

                    b.Property<string>("DominioPersonalizadoTlsStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dominio_personalizado_tls_status");

                    b.Property<string>("DominioPersonalizadoTlsUltimaFalha")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dominio_personalizado_tls_ultima_falha");

                    b.Property<DateTime?>("DominioPersonalizadoTlsUltimaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_tls_ultima_tentativa_em");

                    b.Property<string>("DominioPersonalizadoUltimaFalha")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dominio_personalizado_ultima_falha");

                    b.Property<string>("DominioPersonalizadoUltimaNotificacaoCategoria")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dominio_personalizado_ultima_notificacao_categoria");

                    b.Property<DateTime?>("DominioPersonalizadoUltimaNotificacaoEnviadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_ultima_notificacao_enviada_em");

                    b.Property<string>("DominioPersonalizadoUltimaNotificacaoMotivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dominio_personalizado_ultima_notificacao_motivo");

                    b.Property<string>("DominioPersonalizadoUltimaNotificacaoResultado")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("dominio_personalizado_ultima_notificacao_resultado");

                    b.Property<int>("DominioPersonalizadoUltimaNotificacaoTentativas")
                        .HasColumnType("integer")
                        .HasColumnName("dominio_personalizado_ultima_notificacao_tentativas");

                    b.Property<DateTime?>("DominioPersonalizadoUltimaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_ultima_tentativa_em");

                    b.Property<DateTime?>("DominioPersonalizadoUltimoMonitoramentoDegradadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_ultimo_monitoramento_degradado_em");

                    b.Property<string>("DominioPersonalizadoUltimoMonitoramentoDegradadoMotivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dominio_personalizado_ultimo_monitoramento_degradado_motivo");

                    b.Property<DateTime?>("DominioPersonalizadoUltimoMonitoramentoSaudavelEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_ultimo_monitoramento_saudavel_em");

                    b.Property<DateTime?>("DominioPersonalizadoVerificadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dominio_personalizado_verificado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Publica")
                        .HasColumnType("boolean")
                        .HasColumnName("publica");

                    b.Property<string>("ResumoContato")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("resumo_contato");

                    b.Property<string>("ResumoEndereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("resumo_endereco");

                    b.Property<string>("Slug")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("DominioPersonalizadoAtivo")
                        .IsUnique();

                    b.HasIndex("DominioPersonalizadoDesejado")
                        .IsUnique();

                    b.HasIndex("DominioPersonalizadoProximaTentativaEm");

                    b.HasIndex("DominioPersonalizadoProximoMonitoramentoEm");

                    b.HasIndex("DominioPersonalizadoTlsProximaTentativaEm");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Api.Modules.ProfessionalServiceAssignments.Domain.ProfessionalServiceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("EmpresaId", "ServiceId");

                    b.HasIndex("EmpresaId", "ProfessionalId", "ServiceId")
                        .IsUnique();

                    b.ToTable("professional_service_assignments", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Profissionais.Domain.Profissional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("profissionais", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Servicos.Domain.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Usuarios.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Api.Modules.Bookings.Domain.Booking", b =>
                {
                    b.HasOne("Api.Modules.Empresas.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Profissionais.Domain.Profissional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Servicos.Domain.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Bookings.Domain.BookingFeedback", b =>
                {
                    b.HasOne("Api.Modules.Bookings.Domain.Booking", null)
                        .WithOne()
                        .HasForeignKey("Api.Modules.Bookings.Domain.BookingFeedback", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Empresas.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Profissionais.Domain.Profissional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Disponibilidade.Domain.DisponibilidadeProfissional", b =>
                {
                    b.HasOne("Api.Modules.Profissionais.Domain.Profissional", null)
                        .WithMany()
                        .HasForeignKey("ProfissionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.ProfessionalServiceAssignments.Domain.ProfessionalServiceAssignment", b =>
                {
                    b.HasOne("Api.Modules.Empresas.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Profissionais.Domain.Profissional", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Modules.Servicos.Domain.Servico", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Profissionais.Domain.Profissional", b =>
                {
                    b.HasOne("Api.Modules.Empresas.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Servicos.Domain.Servico", b =>
                {
                    b.HasOne("Api.Modules.Empresas.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Modules.Usuarios.Domain.Usuario", b =>
                {
                    b.HasOne("Api.Modules.Empresas.Domain.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
